### ISSUE TITLE
Cant change  damage color

### ISSUE THREAD

**Issue by adabugra** [rizecookey/CookeyMod#5]
changing damage color makes it invisible and shows it as white in settings

**Comment by CompeyDev** [comment]
CC @rizecookey, any updates?

**Comment by Jes-debug** [comment]
im still having this issue

**Comment by rizecookey** [comment]
The color code for setting the damage color is a bit unintuitive as it works a bit differently from your regular color codes because it also encodes opacity, which means:
- the first two hexadecimal digits encode the opacity (`00` being completely transparent, `FF` being fully opaque)
- the following 6 hexadecimal digits work like a regular color code (two digits each for red, green, and blue)

So if you want to change the damage color but not the opacity, I'd recommend keeping the first two digits the same as the default and only changing the last six (for which you can use a regular HTML color code picker). I might add some sliders in a future update that could make this easier to use, though.

**Comment by CompeyDev** [comment]
Thank you! This is kind of a weird way to encode data into a hex code, would definitely make more sense to use a format like HSL or include sliders as you mentioned for opacity stuff.

**Comment by rizecookey** [comment]
Yeah, the config screen library I use sadly doesn't provide a better color picking component. I've added some sliders myself in release [1.7.8](https://github.com/rizecookey/CookeyMod/releases/tag/1.7.8%2B1.21.1), though.
